### PR TITLE
RHMAP-10100 update to Swift 2.3

### PR DESCRIPTION
**Pull request by jcesarmobile**

### CODE REVIEW

**Comment by jcesarmobile** [comment]
@corinnekrych can you take a look?

**Comment by danbev** [comment]
Updates cleanly and I can run the app without errors. LGTM

**Review by danbev — APPROVED** [review]

**Comment by corinnekrych** [comment]
@jcesarmobile swift2.3 branch and we\re good to go

**Comment by jcesarmobile** [comment]
done

**Comment by corinnekrych** [comment]
+1

**Pull request merged**
